### ISSUE TITLE
Show not correct list devices

### ISSUE THREAD

**Issue by rockChromeCast** [react-native-google-cast/react-native-google-cast#464] opened 2022-11-01 03:15 UTC
**Describe the bug**
Still show the chrome cast device on list devices even though the device turned off the power or connected with another phone

**To Reproduce**
Case 1: 
1. Turn on the power chrome cast 
2. Search device It's appearing on the list of devices
3. Turn off the power chrome cast 
4. Search device The device still appears on the list of devices

Case 2: 
1. First Phone search Chrome Cast 1, connected with Chrome Cast 1
2. Second Phone search, Chrome Cast 1 is still available on the list of Devices

**Comment by petrbela** [comment] 2022-11-01 07:13
This is how it's designed to work.

---

> Search device The device still appears on the list of devices

The list of devices doesn't update dynamically. If you reopen I think it should update the list but just like when looking for a WiFi network to connect, it might still display one that's not available anymore for a short while.

---

> Second Phone search, Chrome Cast 1 is still available on the list of Devices

The cast device is designed to be operated by multiple devices simultaneously (at least Android ones; iOS might kick out the previously connected sender though I'm not sure). 

---

If you have a *strong* case for why it should behave differently, you might try [Support](https://developers.google.com/cast/support). Closing this issue since it's not a bug in this library.

**Closed by petrbela** 2022-11-01 07:13 UTC

**Comment by rockChromeCast** [comment] 2022-11-01 07:30
Thank you so much for your reply
In the first case. I reopen the list of devices many times. After 30 minutes when I turned off the chrome cast. I call 
const listDevices = await discoveryManager.getDevices(); The devices that I turned off still exit in the list of devices

**Comment by petrbela** [comment] 2022-11-01 08:11
This library doesn't cache the result so you'd have to take it up with the SDK team. There's a similar issue https://issuetracker.google.com/issues/126439439 but it doesn't seem like they consider it something to be fixed.
