### ISSUE TITLE
iOS - Channel is not connected or is not registered with a session

### ISSUE THREAD

**Issue by namitonefc** [react-native-google-cast/react-native-google-cast#165] opened 2019-12-08 14:02 UTC
**Describe the bug**
Getting "sendTextMessage error Channel is not connected or is not registered with a session" on iOS. 

Here is the code - 
```
 sendMediaGetMessage() {
    console.debug("entry: sendMediaGetMessage");
    console.debug("WatchV:registering channel " + CastConstant.MESSAGE_CHANNEL);
    GoogleCast.initChannel(CastConstant.MESSAGE_CHANNEL)
      .then(() => {
        console.debug("WatchV:channel init success");
        GoogleCast.sendMessage(
          CastConstant.MESSAGE_CHANNEL,
          JSON.stringify({ intent: "get_media" })
        )
          .then(() => {})
          .catch(error => {
            console.log(error);
          });
      })
      .catch(function(err) {
        console.debug("WatchV:error: sendMediaGetMessage");
        console.log(err);
      });
  }
```
I am getting **channel init success** but later while trying to send message to channel, I get **sendTextMessage error Channel is not connected or is not registered with a session**.

I am using -
pod 'react-native-google-cast/NoBluetooth', path: '../node_modules/react-native-google-cast/ios/'

google-cast-sdk-no-bluetooth (4.4.6)
Xcode 10.3
React native 0.59

Note: Using a custom receiver app for chromecast.

**Comment by petrbela** [comment] 2019-12-08 15:47
Hmm, I'll need to re-test this feature. Thanks for opening the issue.

**Comment by namitonefc** [comment] 2019-12-08 16:17
Thanks @petrbela. I am stuck on this. Looking forward to hearing from you soon.

**Comment by namitonefc** [comment] 2019-12-10 17:22
@petrbela Any update on this?

**Comment by petrbela** [comment] 2019-12-10 18:29
@namitonefc Hey, definitely won't have time to look into it until this weekend, sorry :(

**Comment by namitonefc** [comment] 2019-12-14 11:54
@petrbela Please let me know if you find anything.

**Comment by namitonefc** [comment] 2019-12-21 17:55
@petrbela Any update on this?

**Comment by SUJITHBHAT** [comment] 2020-01-10 13:22
Any update on this?

**Comment by victorhermes** [comment] 2020-01-31 00:40
Same problem. Any update?

**Comment by petrbela** [comment] 2020-01-31 17:31
I'm unfortunately swamped with work (two startups 😔) so if anyone has time to look into this, any help/PRs is welcome!

**Comment by victorhermes** [comment] 2020-02-01 02:56
I remove this snippet of code and and nothing happened. It works. After all, what is the function of initChannel and sendMessage?

`
function sendMessage() {
  const channel = 'urn:x-cast:com.reactnative.googlecast.example';

  GoogleCast.initChannel(channel).then(() => {
    GoogleCast.sendMessage(channel);
  });
}
`

**Comment by petrbela** [comment] 2020-02-01 17:28
@victorhermes It's for sending messages to a custom receiver app. You definitely don't need it unless you're building something custom.

**Comment by victorhermes** [comment] 2020-02-02 14:12
When you say custom receiver app, are you saying chromecast styles?

**Comment by petrbela** [comment] 2020-02-02 19:49
@victorhermes From https://developers.google.com/cast/docs/developers:

A receiver application that handles communication between the sender app and the receiver device. You have the following options:
- The Default Media Receiver presented with the Google Cast branding and styling.
- The Styled Media Receiver for which you can develop the styles and branding. See Styled Media Receiver.
- A **custom receiver**, as described in Custom receiver that implements the Receiver API and handles custom messages from your sender app; it may also interface with the media player types provided through the Media Player Library.

**Comment by aubert-creation** [comment] 2020-03-17 09:03
Any news ? I reproduce this bug and I must use custom message for send params to my receiver app. Or maybe there is a clean solution to send params after CastButton pressed and Session started ? Help me :)

**Comment by hosek** [comment] 2020-06-08 10:42
Check if channel id match on both sides sender/receiver

**Comment by vilius** [comment] 2020-06-12 11:29
I was getting same error but the problem was that I forgot to add Chromecast App ID to AppDelegate.m

```objective-c
NSString *chromecastAppID = [ReactNativeConfig envFor:@"CHROMECAST_APP_ID"];
GCKDiscoveryCriteria *criteria = [[GCKDiscoveryCriteria alloc] initWithApplicationID:chromecastAppID];
```

After that got it working with iOS and Chromecast custom receiver app.

**Comment by petrbela** [comment] 2021-01-02 17:06
This should now be fixed in v4.

**Closed by petrbela** 2021-01-02 17:06 UTC
