### ISSUE TITLE
v4.8.0 of Google's SDK breaks iOS cast button

### ISSUE THREAD

**Issue by gavrichards** [react-native-google-cast/react-native-google-cast#510] opened 2023-10-31 10:53 UTC
**Describe the bug**
I previously [filed a bug](https://github.com/react-native-google-cast/react-native-google-cast/issues/509) saying that the cast button had stopped working in my app but I wasn't sure why. I read that this project refers to v4.7.0 of Google's SDK as being the latest version, and discovered that 4.8.0 is out which has various changes for iOS, so I suggested perhaps this would help.

Later I discovered that in fact I was _already_ using 4.8.0 of the SDK - running `pod update` had installed it without me knowing.

Forcing a downgrade to 4.7.1 of the SDK by editing Podfile.lock and running `pod install` fixes the issue.

**To Reproduce**
1. Set up the example and run `pod update`
2. Check Podfile.lock includes this specific line:   - google-cast-sdk-dynamic-xcframework-no-bluetooth (4.8.0)
3. Run it on iOS
4. Note that tapping the cast button doesn't do anything
5. Edit the line in Podfile.lock and change the version to 4.7.1
6. Run `pod install`, run the app on iOS and this time it will work

**Expected behavior**
As running `pod update` installs the latest SDK from Google by default, it would be great if this library could be updated to support it on iOS.

**Device:**
 - Device: iPhone 13
 - OS: Tested on iOS 16 and iOS 17.1
 - Library Version 4.6.1

**Checklist:**
 - [X] I have followed [Installation](https://react-native-google-cast.github.io/docs/getting-started/installation) and [Setup](https://react-native-google-cast.github.io/docs/getting-started/setup)
 - [X] My problem is not described in [Troubleshooting](https://react-native-google-cast.github.io/docs/getting-started/troubleshooting)
 - [X] I believe the bug is in the React Native Google Cast library, not in the Google Cast SDK. Otherwise please use the official [Google Cast Support](https://developers.google.com/cast/support) as I'm not able to help with native SDK issues.
 - [X] I have searched [existing issues](https://github.com/react-native-google-cast/react-native-google-cast/issues?q=is%3Aissue) and have not found a similar one

**Comment by gramosukaj** [comment] 2023-11-07 15:02
I'm encountering the same issue.

The solution to overwrite "google-cast-sdk-dynamic-xcframework-no-bluetooth" with version "4.7.1" also works.

Device: iPhone 15
OS: Tested on iOS 17.0.3
Library Version 4.6.2

**Comment by sayem314** [comment] 2023-12-05 04:52
Also [google-cast-sdk-dynamic-xcframework-no-bluetooth](https://github.com/react-native-google-cast/google-cast-sdk-dynamic-xcframework-no-bluetooth) seems to be deprecated by @petrbela 

`react-native-google-cast` requires an update now

**Comment by tobbbe** [comment] 2024-01-03 14:07
THANK YOU for posting a solution ❤️❤️❤️❤️

**Comment by sayem314** [comment] 2024-01-03 15:01
Patch with [ds300/patch-package](https://github.com/ds300/patch-package)

```bash
$ cat patches/react-native-google-cast+4.6.2.patch
```
```patch
diff --git a/node_modules/react-native-google-cast/react-native-google-cast.podspec b/node_modules/react-native-google-cast/react-native-google-cast.podspec
index d1948aa..39212a4 100644
--- a/node_modules/react-native-google-cast/react-native-google-cast.podspec
+++ b/node_modules/react-native-google-cast/react-native-google-cast.podspec
@@ -32,7 +32,7 @@ Pod::Spec.new do |s|
 
   s.subspec 'NoBluetoothArm' do |ss|
     ss.dependency "#{package['name']}/RNGoogleCast"
-    ss.dependency 'google-cast-sdk-dynamic-xcframework-no-bluetooth'
+    ss.dependency 'google-cast-sdk-dynamic-xcframework-no-bluetooth', '4.7.1'
   end
 
   s.subspec 'RNGoogleCast' do |ss|
   ```

```bash
$ diff package.json
```

```patch
 "scripts": {
+  "postinstall": "npx patch-package"
 }
 ```

**Comment by petrbela** [comment] 2024-01-29 23:14
It appears the bug is in the SDK itself https://issuetracker.google.com/issues/298066142?pli=1

I'll downgrade/change the dependency and note it in the docs.

**Comment by VahanLab** [comment] 2024-02-09 08:30
Hey @petrbela I've just tested your latest lib release 4.7.0 and the iOS cast button is still broken. Nothing happens on tap on the cast button, and trying to get the list of devices from useDevices() returns an empty array. While I have a Chromecast on my network, reachable with the youtube app.
I see you now use the google-cast-sdk-no-bluetooth-xcframework pod, but using 4.8.0, whereas you pointed out just above that this version was broken.
Thanks a lot for your work

**Comment by petrbela** [comment] 2024-02-10 22:35
`google-cast-sdk-dynamic-xcframework-no-bluetooth` was an official pod created by me because Google hadn't published an xcframework version until 4.8.0. I've now switched the dependency to `google-cast-sdk-no-bluetooth-xcframework` as that is the official package.

As for the cast button being broken, I tested with the latest version and wasn't able to reproduce it. However, I understand it does happen for some people as has officially been confirmed by Google, but that's outside the scope of this package and I'm unfortunately not able to fix it.

With the latest release of this library, since I wasn't able to directly confirm the issue, I've opted to simply update to the official dependencies. For those facing the bug, workarounds have already been discussed and suggested in this issue.

FWIW, I've also been able to build and run the standard non-xcframework pod on an M1 Mac, which is in contrast with what the Google documentation says. As I'm busy working on v5 of this library and figuring out which Google statement is true cost me too much time, I've decided to just present the four pods that Google publishes as [dependency variants of this library](https://react-native-google-cast.github.io/docs/getting-started/installation.html#b-custom-version-or-guest-mode), so that the developer can choose which one works for them.

Lastly, I'd recommend checking whether your app (Podfile) specifies ios version 13.0 or higher which the 4.8.0 Cast SDK now requires. If you need to support older ios versions, you need to use an older version of this lib/SDK.

Hopefully, this clarifies things.

**Comment by Sumeeth-24** [comment] 2024-06-09 05:57
Please fix this issue as early as possible because we have to rollout our OTT app and everything is working in our app except this ios cast button. Even our casting is working good in our android app but just because of this issue we are not able to rollout our app because ios cast button is not working (even though android is working). We are stuck in this. So please release a new version or fix it.

**Comment by noahschwagele** [comment] 2024-06-25 13:30
Hey guys how does one downgrade to SDK v4.7.1?

**Comment by petrbela** [comment] 2024-06-26 08:44
Alright, it seems that the simplest workaround is to not rely on the Cast button and start the discovery process either manually or on app initialization. No need to downgrade.

I've added the following section to the Setup docs:

> Due to a [bug](https://issuetracker.google.com/issues/298066142?pli=1) in the Google Cast SDK v4.8.0 and v4.8.1, pressing the Cast button for the first time doesn't start the discovery process and no Cast dialog is shown (at least on some devices). A workaround is to either set options.startDiscoveryAfterFirstTapOnCastButton = false to initialize discovery as soon as the app is opened, or to explicitly call [startDiscovery](https://react-native-google-cast.github.io/docs/api/classes/discoverymanager#startdiscovery), as described above. This should be fixed in the next release of the SDK.

I'm closing this for now but let me know if you're still experiencing any issues.

**Closed by petrbela** 2024-06-26 08:44 UTC
