### ISSUE TITLE
[iOS] Google Cast not working after killing the app and re-opening it

### ISSUE THREAD

**Issue by nenjamin2405** [react-native-google-cast/react-native-google-cast#151] opened 2019-10-29 03:48 UTC
**Platform**
iOS

**RN Google Cast Version**
3.2.0

**How to reproduce**
The castState is `NotConnected` -->  press on the ChromeCast button to connect --> everything related to Google Cast is working fine at this moment --> Kill the app and re-open it --> `const castState = await GoogleCast.getCastState()` will return`Connected` --> use `const deviceInfo = await GoogleCast.getCastDevice()`, the deviceInfo will be `undefined` --> `GoogleCast.castMedia` and Google Cast related functions not working also.

I can confirm that when I test my old app using the older version `3.1.3` of RN Google Cast, everything is working fine. Hi @petrbela, could you please help me on this, thank you

**Comment by petrbela** [comment] 2019-10-29 10:29
Hey, sorry, I don't seem to be able to reproduce this. After killing the app and reopening, it automatically rejoins the previous session. Also, there wasn't any relevant change in the iOS code between 3.1.3 and 3.2.0 other than updating the SDK. Maybe the issue is flaky?

If you experience it consistently, can you make an example project so we can pinpoint the problem?

**Comment by nenjamin2405** [comment] 2019-10-30 09:14
@petrbela Sorry for this phrase 
```
I can confirm that when I test my old app using the older version 3.1.3 of RN Google Cast, everything is working fine
```

Actually, the old working app is an Android app. not an iOS app, so I'm not sure whether this problem is available on iOS in the older version of RN Google Cast. 

I already tried to create a whole new RN project and integrated RN Google Cast's latest version, and I saw that `await GoogleCast.getCastDevice()` returned `undefined` if I connected then close and reopen the app, you can try it :(

**Comment by nenjamin2405** [comment] 2019-11-08 02:02
Hi @petrbela, did you try to start the app from scratch and integrate the RNGoogleCast to test the `undefined` problem of the `await GoogleCast.getCastDevice()`

**Comment by hoang-rio** [comment] 2020-01-25 15:04
Any update? I have same issue

**Comment by joeyscarim** [comment] 2020-02-26 23:40
I am experiencing this also.

GoogleCast.getCastState() is "Connected", but trying to do anything after that, or even  GoogleCast.endSession(); does not work.

**Comment by marcusstenbeck** [comment] 2020-04-09 09:08
@joeyscarim What error are you getting when doing `GoogleCast.endSession()`? Is it the `No castSession!` error?

**Comment by marcusstenbeck** [comment] 2020-04-09 09:08
I think #185 is related to this.

**Comment by redreceipt** [comment] 2020-05-05 19:11
+1 on this issue

**Comment by dcalhoun** [comment] 2020-07-02 14:58
I believe I have been able to identify why this issue is occurring for some. I have outlined some of those details in #207.

If you place the code to [initialize the Cast context](https://developers.google.com/cast/docs/ios_sender/integrate#initialize_the_cast_context), which is outlined in the `react-native-google-cast` [setup documentation](https://github.com/react-native-google-cast/react-native-google-cast#setup), _after_ the code to initialize React Native root view, then a race condition is created where [`RNGoogleCast.m`](https://github.com/react-native-google-cast/react-native-google-cast/blob/71dae0b74421513959394470fa64fe9f04a979f5/ios/RNGoogleCast/RNGoogleCast.m#L27) is sometimes initialized _before_ the React Native `AppDelegate.m` has created the Cast context.

## Diff

```diff
diff --git a/example/ios/RNGoogleCastExample/AppDelegate.m b/example/ios/RNGoogleCastExample/AppDelegate.m
index f98cadc..5ec4d1a 100644
--- a/example/ios/RNGoogleCastExample/AppDelegate.m
+++ b/example/ios/RNGoogleCastExample/AppDelegate.m
@@ -22,16 +22,16 @@
                                                    moduleName:@"RNGoogleCastExample"
                                             initialProperties:nil];  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
 
+  // Initialize Google Cast
+  GCKDiscoveryCriteria *criteria = [[GCKDiscoveryCriteria alloc] initWithApplicationID:kGCKDefaultMediaReceiverApplicationID];
+  GCKCastOptions* options = [[GCKCastOptions alloc] initWithDiscoveryCriteria:criteria];
+  [GCKCastContext setSharedInstanceWithOptions:options];
+
   self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
   UIViewController *rootViewController = [UIViewController new];
   rootViewController.view = rootView;
   self.window.rootViewController = rootViewController;
   [self.window makeKeyAndVisible];
-
-  // Initialize Google Cast
-  GCKDiscoveryCriteria *criteria = [[GCKDiscoveryCriteria alloc] initWithApplicationID:kGCKDefaultMediaReceiverApplicationID];
-  GCKCastOptions* options = [[GCKCastOptions alloc] initWithDiscoveryCriteria:criteria];
-  [GCKCastContext setSharedInstanceWithOptions:options];
   return YES;
 }
```

<details>
<summary>willFinishLaunchingWithOptions Alternative</summary>

```diff
diff --git a/example/ios/RNGoogleCastExample/AppDelegate.m b/example/ios/RNGoogleCastExample/AppDelegate.m
index 5ec4d1a..ee53cba 100644
--- a/example/ios/RNGoogleCastExample/AppDelegate.m
+++ b/example/ios/RNGoogleCastExample/AppDelegate.m
@@ -15,6 +15,15 @@
 
 @implementation AppDelegate
 
+- (BOOL)application:(UIApplication *)application willFinishLaunchingWithOptions:(NSDictionary *)launchOptions
+{
+  // Initialize Google Cast
+  GCKDiscoveryCriteria *criteria = [[GCKDiscoveryCriteria alloc] initWithApplicationID:kGCKDefaultMediaReceiverApplicationID];
+  GCKCastOptions* options = [[GCKCastOptions alloc] initWithDiscoveryCriteria:criteria];
+  [GCKCastContext setSharedInstanceWithOptions:options];
+  return YES;
+}
+
 - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
 {
   RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
@@ -22,11 +31,6 @@
                                                    moduleName:@"RNGoogleCastExample"
                                             initialProperties:nil];  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
 
-  // Initialize Google Cast
-  GCKDiscoveryCriteria *criteria = [[GCKDiscoveryCriteria alloc] initWithApplicationID:kGCKDefaultMediaReceiverApplicationID];
-  GCKCastOptions* options = [[GCKCastOptions alloc] initWithDiscoveryCriteria:criteria];
-  [GCKCastContext setSharedInstanceWithOptions:options];
-
   self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
   UIViewController *rootViewController = [UIViewController new];
   rootViewController.view = rootView;

```

</details>

## Full `AppDelegate.m` Examples

<details>
<summary>Bad</summary>

```obj-c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"RNGoogleCastExample"
                                            initialProperties:nil];  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  // Initialize Google Cast
  GCKDiscoveryCriteria *criteria = [[GCKDiscoveryCriteria alloc] initWithApplicationID:kGCKDefaultMediaReceiverApplicationID];
  GCKCastOptions* options = [[GCKCastOptions alloc] initWithDiscoveryCriteria:criteria];
  [GCKCastContext setSharedInstanceWithOptions:options];
  return YES;
}
```

</details>

<details>
<summary>Good</summary>

```obj-c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"RNGoogleCastExample"
                                            initialProperties:nil];  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  // Initialize Google Cast
  GCKDiscoveryCriteria *criteria = [[GCKDiscoveryCriteria alloc] initWithApplicationID:kGCKDefaultMediaReceiverApplicationID];
  GCKCastOptions* options = [[GCKCastOptions alloc] initWithDiscoveryCriteria:criteria];
  [GCKCastContext setSharedInstanceWithOptions:options];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}
```

</details>

<details>
<summary>willFinishLaunchingWithOptions Alternative</summary>

```obj-c
- (BOOL)application:(UIApplication *)application willFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // Initialize Google Cast
  GCKDiscoveryCriteria *criteria = [[GCKDiscoveryCriteria alloc] initWithApplicationID:kGCKDefaultMediaReceiverApplicationID];
  GCKCastOptions* options = [[GCKCastOptions alloc] initWithDiscoveryCriteria:criteria];
  [GCKCastContext setSharedInstanceWithOptions:options];
  return YES;
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"RNGoogleCastExample"
                                            initialProperties:nil];  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}
```

</details>

**Comment by petrbela** [comment] 2020-07-05 20:05
@dcalhoun This would make a lot of sense. I'm actually not sure why the initialization code was ever placed at the end when all 3rd party native libraries should initialize before RN. I've just updated the examples appropriately.

@redreceipt @marcusstenbeck @hoang-rio @nenjamin2405 Can you guys see if it fixes the problem for you?

**Comment by hoang-rio** [comment] 2020-08-02 02:20
> @dcalhoun This would make a lot of sense. I'm actually not sure why the initialization code was ever placed at the end when all 3rd party native libraries should initialize before RN. I've just updated the examples accordingly.
> 
> @redreceipt @marcusstenbeck @hoang-rio @nenjamin2405 Can you guys see if it fixes the problem for you?

Nothing change. No cast session error exists after restart app

**Comment by demianp** [comment] 2020-08-27 17:37
hey guys, please check this solution:
https://github.com/react-native-google-cast/react-native-google-cast/pull/188#issuecomment-682090063

**Comment by petrbela** [comment] 2022-02-27 16:24
This issue is outdated, closing.

**Closed by petrbela** 2022-02-27 16:24 UTC
