### ISSUE TITLE
IOS - Volume keys not working

### ISSUE THREAD

**Issue by goncalo-assuncao** [react-native-google-cast/react-native-google-cast#260] opened 2020-12-30 10:48 UTC
**Describe the bug**
The physical volume keys are not working in IOS.

**Versions:**
- RNGC Library Version: 3.4.0

**To Reproduce**
1- Start a playback in chromecast
2- Press the volume physical controls

**Expected behavior**
Chromecast volume to change accordingly

**Additional context**
The configuration that I'm using, when initiating, in the `AppDelegate.m` file, the context is:

```
  NSString *chromecastAppId = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSCHROMECASTAPPID"];
  GCKDiscoveryCriteria *criteria = [[GCKDiscoveryCriteria alloc] initWithApplicationID:chromecastAppId];
  GCKCastOptions* options = [[GCKCastOptions alloc] initWithDiscoveryCriteria:criteria];
  options.physicalVolumeButtonsWillControlDeviceVolume = YES;
  options.stopReceiverApplicationWhenEndingSession = NO;
  [GCKCastContext setSharedInstanceWithOptions:options];
  [GCKCastContext sharedInstance].useDefaultExpandedMediaControls = YES;

  GCKUIExpandedMediaControlsViewController *controllerInstance = [GCKCastContext sharedInstance].defaultExpandedMediaControlsViewController;
  [controllerInstance setButtonType:GCKUIMediaButtonTypeNone atIndex:0 ];`
```

**Comment by raymondjacobson** [comment] 2022-03-25 01:46
+1 this does not work

**Comment by petrbela** [comment] 2022-03-25 01:55
This appears to be an issue in the Cast SDK https://issuetracker.google.com/issues/202423437?pli=1

Closing this as it's not a bug in this library. Please follow the discussion on Google's tracker for updates.

**Closed by petrbela** 2022-03-25 01:55 UTC

**Comment by raymondjacobson** [comment] 2022-03-25 01:57
Thanks @petrbela !

**Comment by KaterynaPotrusRedge** [comment] 2023-10-04 12:24
The Google Cast iOS SDK in version 4.8.0 has already a fix for this issue. Can I update iOS SDK somehow or should I wait this library to be updated?

**Comment by petrbela** [comment] 2023-10-04 12:30
I think if you're using the `google-cast-sdk` pod, it should pull the latest version automatically. But I think currently the default dependency is set to the `google-cast-sdk-dynamic-xcframework-no-bluetooth` which I built manually so I'll need to update it. See https://react-native-google-cast.github.io/docs/getting-started/installation.html#ios

**Comment by KaterynaPotrusRedge** [comment] 2023-10-04 12:31
@petrbela thank you very much!

**Comment by KaterynaPotrusRedge** [comment] 2023-10-04 14:28
Unfortunately for me after update the issue is still valid. (Got `google-cast-sdk-dynamic-xcframework-no-bluetooth` update to 4.8.0)
