### ISSUE TITLE
"RNGoogleCastButton" was not found in the UIManager

### ISSUE THREAD

**Issue by DennisdeWitNL** [react-native-google-cast/react-native-google-cast#341] opened 2021-06-24 17:12 UTC
Okay, so I got a very strange problem. I have successfully setup the module in my app. It works on iOS, I see the button, can cast, everything is great. Then I built an APK for my Samsung Galaxy S10. I saw the castbutton, clicked it, everything worked and it started casting as it should.

But then I tried the same thing in the Android Studio Emulator. I am using Pixel XL API 30. It is running Android 11.0. When I try to open the React Native screen with the <CastButton /> hook, it says there is a problem. It is an Component Exception: requireNativeComponent: "RNGoogleCastButton was not found in the UIManager."

I do not run against this problem on my Samsung Galaxy S10, just in the emulator. Is this some kind of bug in the module? Can I safely ignore this, or should I wait with releasing the app until this problem was solved? Did I do something wrong that I should doublecheck?

Thank you,
Dennis

**Comment by petrbela** [comment] 2021-06-24 17:27
Hi! I have not seen this error before. Let me see if I can reproduce.

Btw just to double-check, are you using a simulator that has Play Services installed (in the Play Store column it should show the Play icon)?

**Comment by DennisdeWitNL** [comment] 2021-06-24 17:38
> Hi! I have not seen this error before. Let me see if I can reproduce.
> 
> Btw just to double-check, are you using an emulator that has Play Services installed (in the Play Store column it shows the Play icon)?

Hi. Yes, I am running Pixel 4 API 30 with Play Store now. I can run the Play Store, I just run against this issue on this version, too. I double checked the manual and everything is correct.

**Comment by petrbela** [comment] 2021-06-24 18:53
To be honest, I haven't been able to test the Cast library on an emulator since I switched to an M1 Mac a few weeks ago (it displays the icon but doesn't find any devices). I wanna say it's *probably* fine as long as it works on a real device...

Also, your error seems like you need to build a new version of the app from Android Studio (or `react-native run-android`).

**Comment by DennisdeWitNL** [comment] 2021-06-24 19:37
I ran react-native run-android and still had the same problem. I don't have this problem on iOS, just on Android. I tried again on an Android smartphone, and everything was fine. Just not in the emulator. So probably, I should not care much about the problem, then. :)

Maybe you can leave this issue open until you verify if my issue is valid. I am running the emulator on an MacBook Pro with Intel processor.

**Comment by lucasmpalomanes** [comment] 2021-07-11 18:13
I'm having the same problem, even when running on a real device; it just crashes when <CastButton> is supposed to be rendered

**Comment by Trialguladog** [comment] 2021-08-11 08:33
@ hello everyone, 

I have the same Problem on Android Real Device.
i try to fix that since 2 month.
Can someone help?

And it will also not work on Ios Realevice.
Maybee you cann help "DennisdeWitNL".

Thanks for your help

**Comment by DennisdeWitNL** [comment] 2021-08-11 09:15
I don’t have this problem on real devices. Did you follow all the instructions of the guide? On iOS I have 0 problems.

**Comment by Trialguladog** [comment] 2021-08-11 09:45
@DennisdeWitNL Yes, i followed the instruction many times.  But i get the error, that the RNGoogleCastButton is not in the UI-Manager.

I can import it, but when i write it in the render area, it crashes on Android.

On IOS it crashes, when i import it.

thanks for your help

**Comment by petrbela** [comment] 2021-08-11 13:49
@Trialguladog Could you create an example project where I could reproduce the error?

**Comment by Trialguladog** [comment] 2021-08-11 18:55
@petrbela I have done the following on my HomescreenSide:

import React, { useReducer } from "react";
import {Text,View,Image,ImageBackground} from "react-native";
import { ScrollView, TouchableOpacity } from "react-native-gesture-handler";
import mycolors from "../components/colors";
import firebase from "firebase";
import "firebase/firebase-app";
import Global from "../components/global.js";
import { snapshotToArray } from "../helpers/firebaseHelpers";
import { firebaseConfig } from "../config/config";
import GoogleCast, { CastButton } from 'react-native-google-cast';

class HomeScreen extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      currentUser: "",
      countrelaxtitles: Global.relaxtitleainfo.length,
      countactivtitles: Global.activtitleainfo.length,
    };
    this._isMounted = false;
  }

// ############   Cast-Funktionen zum testen    #############
  playCast = () => GoogleCast.play(); 
  pauseCast = () => GoogleCast.pause();
  shwoControls = () => GoogleCast.launchExpandedControls();
  startCast = (video, image, title, subtitle, duration, currentTime, mediaType, moreDetails) => {
  GoogleCast.castMedia({
    mediaUrl: video, // Stream media video uri
    imageUrl: image, // Image video representative uri
    title, // Media main title
    subtitle, // Media subtitle
    studio: 'Asap Developers', // Media or app owner
    streamDuration: duration, // Stream duration in seconds
    contentType: mediaType, // Optional media type, default is 'video/mp4'
    playPosition: currentTime, // Stream play position in seconds
    customData: {
      // Optional, your custom object that will be passed to as customData to reciever
      mediaDetails: moreDetails,
    },
  })
    .then(console.log('Playing.. '))
    .catch(e => console.log('An error has ocurred, reason: ', e));
};
// ##########################################################
  

  checkIfLoggedIn = () => {
    if (!firebase.apps.length) {
      firebase.initializeApp(firebaseConfig);
    } else {
      firebase.app();
    }
    this.unsubscribe = firebase.auth().onAuthStateChanged((user) => {
      if (user) {
        this.setState({ currentUser: user.name });
      } else {
        this.props.navigation.navigate("WelcomeScreen");
      }
    });
  };

  componentDidMount = async () => {
    this._isMounted = true;
    const { navigation } = this.props;
    const user = navigation.getParam("user");
    this.checkIfLoggedIn();

    const currentUserData = await firebase
      .database()
      .ref("users")
      .child(user.uid)
      .child("userdata")
      .once("value");
    Global.StringCurrentUserData = currentUserData;
    Global.StringUserDataInfo = snapshotToArray(currentUserData);
    this.setState({
      currentUser: " " + Global.StringUserDataInfo[2],
    });

    const currentanimalData = await firebase
      .database()
      .ref("users")
      .child(user.uid)
      .child("animaldata")
      .once("value");
    Global.StringCurrentAnimalData = currentanimalData;
    Global.StringCurrentAnimalInfo = snapshotToArray(currentanimalData);

    const relaxasongs = await firebase
      .database()
      .ref("songs")
      .child("relax")
      .child("relaxa")
      .once("value");
    Global.relaxtitleainfo = snapshotToArray(relaxasongs);
    const relaxbsongs = await firebase
      .database()
      .ref("songs")
      .child("relax")
      .child("relaxb")
      .once("value");
    Global.relaxtitlebinfo = snapshotToArray(relaxbsongs);
    const relaxcsongs = await firebase
      .database()
      .ref("songs")
      .child("relax")
      .child("relaxc")
      .once("value");
    Global.relaxtitlecinfo = snapshotToArray(relaxcsongs);

    const activasongs = await firebase
      .database()
      .ref("songs")
      .child("activ")
      .child("activa")
      .once("value");
    Global.activtitleainfo = snapshotToArray(activasongs);
    const activbsongs = await firebase
      .database()
      .ref("songs")
      .child("activ")
      .child("activb")
      .once("value");
    Global.activtitlebinfo = snapshotToArray(activbsongs);
    const activcsongs = await firebase
      .database()
      .ref("songs")
      .child("activ")
      .child("activc")
      .once("value");
    Global.activtitlecinfo = snapshotToArray(activcsongs);

    const noisesongs = await firebase
      .database()
      .ref("songs")
      .child("noise")
      .once("value");
    Global.noisetitleinfo = snapshotToArray(noisesongs);
  };

  componentDidUpdate(prevProps, prevState) {}

  componentWillUnmount() {
    this._isMounted = false;
  }

  state = {modalVisible: false};

  setModalVisible = (visible) => {
    this.setState({ modalVisible: visible });
  };

  siteopenr() {
    Global.Stringmode = "Entspannung";
    Global.loadtitlea = Global.relaxtitleainfo;
    Global.loadtitleb = Global.relaxtitlebinfo;
    Global.loadtitlec = Global.relaxtitlecinfo;
    Global.imagebackgroundmedia = require("../images/relaxscreen.png");
    Global.Stringcolor = mycolors.mainblue;
    Global.playbuttoncolor = require("../icons/playblue2.png");
    Global.pausebuttoncolor = require("../icons/pauseblue2.png");
    this.props.navigation.navigate("MediathekScreen");
  }

  siteopena() {
    Global.Stringmode = "Aktivierung";
    Global.loadtitlea = Global.activtitleainfo;
    Global.loadtitleb = Global.activtitlebinfo;
    Global.loadtitlec = Global.activtitlecinfo;
    Global.imagebackgroundmedia = require("../images/activscreen.png");
    Global.Stringcolor = mycolors.maingreen;
    Global.playbuttoncolor = require("../icons/playgreen2.png");
    Global.pausebuttoncolor = require("../icons/pausegreen2.png");
    this.props.navigation.navigate("MediathekScreen");
  }

  siteopenn() {
    Global.Stringmode = "Geräusche";
    Global.imagebackgroundmedia = require("../images/noisescreen.png");
    Global.Stringcolor = mycolors.mainpurple;
    Global.playbuttoncolor = require("../icons/playpink2.png");
    Global.pausebuttoncolor = require("../icons/pausepink2.png");
    this.props.navigation.navigate("AudioPlayerScreen");
  }

  render() {
    const { modalVisible } = this.state;
    return (
      <ImageBackground
        source={require("../images/homescreen.png")}
        style={{ width: "100%", height: "100%", resizeMode: "stretch" }}>
        <View style={{ flex: 1 }}>
          <View style={{ width: "100%", position: "absolute", bottom: "35%" }}>
            <View style={{ flexDirection: "row", justifyContent: "center" }}>
              <View
                style={{
                  position: "absolute",
                  left: "5%",
                  flexDirection: "row"}}>
                <Text style={{ color: "white", fontSize: 25 }}>Hello</Text>
                <Text style={{ color: "white", fontSize: 25 }}>
                  {this.state.currentUser},
                </Text>
              </View>
              <View
                style={{
                  flexDirection: "row",
                  justifyContent: "center",
                  position: "absolute",
                  right: "5%"}}>
                <TouchableOpacity
                  onPress={() => alert(Global.StringUserDataInfo[2])}>
                  <Image
                    source={require("../icons/notification_white.png")}
                    style={{ width: 28, height: 28, marginRight: 10 }}/>
                </TouchableOpacity>
                <TouchableOpacity
                  onPress={
                    () => this.props.navigation.openDrawer()}>
                  <Image
                    source={require("../icons/menue_white.png")}
                    style={{ width: 28, height: 28 }}/>
                </TouchableOpacity>
              </View>
            </View>
          </View>
          <Image
            source={require("../icons/linie.png")}
            style={{
              width: "90%",
              alignSelf: "center",
              position: "absolute",
              bottom: "10%"}}/>
        </View>

        <View
          style={{
            flex: 4,
            width: "100%",
            height: "80%",
            shadowColor: "black",
            shadowOffset: { height: 3 },
            shadowOpacity: 0.8,
            shadowRadius: 5,
            backgroundColor: "white",
            justifyContent: "flex-end",
            borderTopLeftRadius: 40,
            borderTopRightRadius: 40}}>
          <ScrollView vertical={true} style={{ margin: 5 }}>
            <View style={{ flexDirection: "row", alignitems: "center" }}>
              <View style={{ flex: 3, paddingLeft: "5%" }}>
                <Text
                  style={{
                    color: "black",
                    fontSize: 20,
                    paddingTop: "5%",
                    fontWeight: "bold"}}>
                  Musik
                </Text>
                <Text style={{ color: "black", fontSize: 15 }}>
                  Wähle eine Stimmung in die
                </Text>
                <Text style={{ color: "black", fontSize: 15 }}>
                  dein Tier hineinversetzt werden soll.
                </Text>
              </View>
              <View style={{ flex: 1, justifyContent: "center" }}>
              <CastButton style={{height: 40, width: 40}} />          

// ########  after i import the CastButton Line, i get the error
//
//     Invariant Violation: requireNativeComponent: "RNGoogleCastButton" was not found in the UIManager.

//     This error is located at:
//         in NavigationContainer (at App.js:33)
//         in App (created by ExpoRoot)
//         in ExpoRoot (at renderApplication.js:45)
//         in RCTView (at View.js:34)
//         in View (at AppContainer.js:106)
//         in RCTView (at View.js:34)
//        in View (at AppContainer.js:132)
//         in AppContainer (at renderApplication.js:39)        

//   ###############################

              </View>
            </View>

            <ScrollView
              horizontal
              showsHorizontalScrollIndicator={false}
              style={{
                marginHorizontal: 0,
                marginTop: 20}}>
              <TouchableOpacity
                onPress={() => this.siteopenr()}
                style={{ height: 220, marginHorizontal: 10, width: 170 }}>
                <ImageBackground
                  source={require("../images/relax.png")}
                  style={{ width: "100%", borderRadius: 15, height: "100%" }}>
                  <Text
                    style={{
                      color: "white",
                      alignSelf: "baseline",
                      paddingLeft: 10,
                      paddingTop: 10,
                      fontSize: 20}}>
                    Entspannung
                  </Text>
                  <View
                    style={{
                      flexDirection: "row",
                      height: "50%",
                      paddingLeft: 10}}>
                    <Image
                      source={require("../icons/music-note_white.png")}
                      style={{
                        width: "15%",
                        height: "20%",
                        justifyContent: "center",
                        resizeMode: "stretch",
                        alignSelf: "stretch"}}/>
                    <Text
                      style={{ color: "white", paddingTop: 5, fontSize: 10 }}>
                      {Global.relaxtitleainfo.length} Lieder verfügbar
                    </Text>
                  </View>
                </ImageBackground>
              </TouchableOpacity>

              <TouchableOpacity
                onPress={() => this.siteopena()}
                style={{ height: 220, marginHorizontal: 10, width: 170 }}>
                <ImageBackground
                  source={require("../images/activ.png")}
                  style={{ width: "100%", borderRadius: 15, height: "100%" }}>
                  <Text
                    style={{
                      color: "white",
                      alignSelf: "baseline",
                      paddingLeft: 10,
                      paddingTop: 10,
                      fontSize: 20}}>
                    Aktivierung
                  </Text>
                  <View
                    style={{
                      flexDirection: "row",
                      height: "50%",
                      paddingLeft: 10}}>
                    <Image
                      source={require("../icons/music-note_white.png")}
                      style={{
                        width: "15%",
                        height: "20%",
                        justifyContent: "center",
                        resizeMode: "stretch",
                        alignSelf: "stretch"}}/>
                    <Text
                      style={{ color: "white", paddingTop: 5, fontSize: 10 }}>
                      {Global.activtitleainfo.length} Lieder verfügbar
                    </Text>
                  </View>
                </ImageBackground>
              </TouchableOpacity>

              <TouchableOpacity
                onPress={() => this.siteopenn()}
                style={{ height: 220, marginHorizontal: 10, width: 170 }}>
                <ImageBackground
                  source={require("../images/noise.png")}
                  style={{ width: "100%", borderRadius: 15, height: "100%" }}>
                  <Text
                    style={{
                      color: "white",
                      alignSelf: "baseline",
                      paddingLeft: 10,
                      paddingTop: 10,
                      fontSize: 20}}>
                    Geräusche
                  </Text>
                </ImageBackground>
              </TouchableOpacity>
            </ScrollView>
          </ScrollView>
        </View>
      </ImageBackground>
    );
  } 
}
export default HomeScreen;

**Comment by Trialguladog** [comment] 2021-08-11 18:57
Sorry for the bad programming, I do this in my spare time and teach myself everything and will clean it up in the end.

**Comment by petrbela** [comment] 2021-08-11 22:08
@Trialguladog It seems you might be using version 3 of the library? Can you upgrade to v4? Documentation over at https://react-native-google-cast.github.io/docs/getting-started/installation.html

**Comment by Trialguladog** [comment] 2021-08-12 16:13
@petrbela thanks for that information, i have done it after these site before also.

How can i check that i am using v4?

I repeated everything from the site, but get the same error.

i hope that you can help me, that is really important for me.

**Comment by petrbela** [comment] 2021-08-12 16:27
`GoogleCast.play()`, `GoogleCast.pause()`, and `GoogleCast.castMedia()` are from the old version. In the new version you call these through the `client` which you obtain as described in https://react-native-google-cast.github.io/docs/getting-started/usage.

That itself wouldn't cause the problem you're seeing but it suggests to me that there's something off with the code. You can see the version of the package you're using in `package.json` and also in `Podfile.lock`, just search for `react-native-google-cast`.

**Comment by Trialguladog** [comment] 2021-08-12 19:41
i checked everything and have ther version 4 in both files.

I removed the ...play, ...pause,....castMedia function and replaced it in with the client method.

But the Error is the same like you said.

Did you have any idea with the UI-Manager makes these problems?

**Comment by Trialguladog** [comment] 2021-08-14 10:10
Can you also explain what the differenz between using guest mode and not?

Maybe these can be the mistake?

**Comment by Trialguladog** [comment] 2021-08-14 10:23
And can you tell me, what this means:

This works if you're extending ReactActivity (or NavigationActivity if you're using react-native-navigation). If you're extending a different activity, make sure it is a descendant of androidx.appcompat.app.AppCompatActivity.

**Comment by petrbela** [comment] 2021-08-14 17:40
I don't think the guest mode or the ReactActivity are relevant for your use case unless you're doing something really advanced.

Do you think you could post the whole project on Github if it's not private? Or at least the relevant native sections AppDelegate.m, MainActivity.java, MainApplication.java, and build.gradle?

**Comment by Trialguladog** [comment] 2021-08-14 18:30
[Data_Trialgula_Github.zip](https://github.com/react-native-google-cast/react-native-google-cast/files/6987021/Data_Trialgula_Github.zip)

**Comment by Trialguladog** [comment] 2021-08-14 18:33
I can not send the while project, only private to you, if it is necessary.

But i catched all relevant data you has written in the Zip File below.

i hope you find my mistake, i will be grateful accordingly   ;)

thank you very much

**Comment by petrbela** [comment] 2021-08-14 18:38
Hmm are you by any chance testing this in the Expo Go app? That won't work as it requires a dedicated app build for the native dependencies.

**Comment by Trialguladog** [comment] 2021-08-14 21:21
Yes i am testing this in expo.

Can i test it than with react-native run- android on real device?

Or how can i check that?

**Comment by petrbela** [comment] 2021-08-14 21:22
Yes, you need to test using run-ios or run-android, ideally on a real device.

**Comment by DennisdeWitNL** [comment] 2021-08-14 21:28
@Trialguladog Sure you can. Get an Android phone and enable Developer Options by tapping 10 times on the serial number of your Device Info. 

Then go to Developer Options and enable USB Debugging. Then go to Android Studio, load the project by dragging the android folder and select your device. Click the playbutton. 

I am using macOS. In Terminal, I write ‘adb shellinput keyevent 82’. A menu will popup inside your app, where you can select the Location option. Fill in your IP-address of the server you are running Metro Bundler on (by performing react-native start). Click LogCat in Android Studio for more detailled debugging.  

Then you should be good to go. On iOS it is even easier. Just use Xcode, connect your iPhone Device and go to Product >> Edit Scheme >> set it to ‘Debug’. Press play. Your iOS app will be installed and run automatically. You don’t need to change any setting and the Metro Bundler will open by itself.

**Comment by petrbela** [comment] 2021-08-14 21:30
Btw it will also be possible to use this library in managed Expo (without having to eject) using expo-dev-client but I haven't had time to support it yet.

But yes this explains why it is failing. I'll close the issue now.

**Closed by petrbela** 2021-08-14 21:30 UTC
Labels: android

**Comment by Trialguladog** [comment] 2021-08-22 10:51
Hello, everyone,

sorry for this late reply.

@ DennisdeWitNL I tried to do this with Android Studio and XCode but got some errors there.

Android: It gave me an error with the FirebaseInstanceId and InstanceIdResult while creating it.
Do you know why?

IOS: Signing for "...." requires a development team. Select a development area in the Signing & Capabilities Editor.
But when I do that, I get a status that my team doesn't support push notifications and is accessing WiFi information.

I have no experience with XCode.

can someone help?

@petrbela Or is it possible to get information to proceed with the expo.

many thanks to you both

**Comment by DennisdeWitNL** [comment] 2021-08-22 10:54
Android, no idea. For Xcode you need to add these capabilities to your app on developer.apple.com. However, it has nothing to do with bugs, so I can’t help you with that on this issue on Github.

**Comment by Trialguladog** [comment] 2021-08-22 11:09
Where i can add the capabilities on developer.apple.com?

i am on the site, but did not found a way to do that

**Comment by Trialguladog** [comment] 2021-08-25 16:36
So, i found it now.

I hope it will work in expo also soon. xD

**Comment by Trialguladog** [comment] 2021-09-25 10:58
Hi @DennisdeWitNL  and @petrbela.

I have no solution in this moment.

Is one of you interested to implement the Function in my Project for Money?

**Comment by petrbela** [comment] 2021-12-17 21:27
Apparently, it seems Expo should already be supported https://github.com/expo/config-plugins/tree/master/packages/react-native-google-cast. Thanks, @EvanBacon!

**Comment by luisfuertes** [comment] 2023-02-08 12:36
I have this problem too:

Im using iOS
Im not using Expo
My app versions:
```
    "react": "17.0.1",
    "react-native": "0.64.4",
    "react-native-google-cast": "^4.6.2",
```

My button code (client value is null)
```
type Props = {
  videoUrl: string,
  videoType?: string,
  style?: ViewStyle,
}

const ButtonCast: FC<Props> = ({ videoUrl, videoType = 'video/mp4', style = {} }) => {
  const client = useRemoteMediaClient()

  if (client) {
    client.loadMedia({
      mediaInfo: {
        contentUrl:
          'https://jsoncompare.org/LearningContainer/SampleFiles/Video/MP4/Sample-MP4-Video-File-for-Testing.mp4',
        contentType: videoType,
      },
    })
  }
  console.log({ client })

  return <CastButton />
}

export default ButtonCast
```

The log:
```
Invariant Violation: requireNativeComponent: "RNGoogleCastButton" was not found in the UIManager.

This error is located at:
    in RNGoogleCastButton (at CastButton.tsx:19)
    in CastButton (at view.tsx:28)
    in ButtonCast (at view.tsx:64)
    in RCTView (at View.js:34)
```
