### ISSUE TITLE
Upgrade Google Cast SDK to v4.5.0

### ISSUE THREAD

**Issue by jacob-israel-turner** [react-native-google-cast/react-native-google-cast#221] opened 2020-09-16 20:52 UTC
**Is your feature request related to a problem? Please describe.**
Not a problem I've encountered, [but one that Google has documented](https://developers.google.com/cast/docs/ios_sender/ios_permissions_changes#ios_14).

**Describe the solution you'd like**
According to the Google Cast guidelines, we should upgrade the Google Cast SDK to v4.5.0.

**Describe alternatives you've considered**
N/A

**Additional context**
Apparently issues will not be present until you try to build on XCode >= 11.7 or targeting iOS 14 or higher.  Would be good to get ahead of this issue so that, as people upgrade, the library does not break.

**Comment by luis-f-lins** [comment] 2020-09-22 13:23
One thing I noticed: at least for me, the `CastButton` is not showing up when I build my app on an iPhone running iOS 14.0. The button is correctly displayed on an iPhone on 12.0, and on multiple Android devices, though. I believe that this might have something to do with this iOS change, because, AFAIK, the button does not show up if the app does not detect any Chromecast devices, and starting on iOS 14, the app will only be able to locate devices when the Google Cast SDK is upgraded to v4.5.0.

I would greatly appreciate if other people who are running iOS 14.0 would confirm if they are also having this problem with the `CastButton`.

**Comment by nbennink** [comment] 2020-09-24 09:54
I experience this problem as well. I'm running my own fork of react-native-google-cast where I changed the cast sdk to <= 4.5.0. Although I would prefer to change it to `= 4.5.0` it might be confusing that different users of this library use different versions of the cast SDK. 
https://github.com/react-native-google-cast/react-native-google-cast/blob/master/ios/react-native-google-cast.podspec#L22

Also note that these changes are required to make cast SDK 4.5.0 work with your app. This is not a change that can be added to the library but should be added to your app instead.
https://developers.google.com/cast/docs/ios_sender/ios_permissions_changes#updating_your_app_on_ios_14

I think this should be enough to upgrade to V4.5.0. Can you check if this works for you?

A problem I still have is when I call: `GoogleCast.showCastPicker();` or `GoogleCast.getCastState();` which will always return `NoDevicesAvailable`. These two methods completely ignore the new network device access permission. I have to look into that more because I think it requires a larger fix.

**Comment by petrbela** [comment] 2020-11-03 11:44
Using the latest version of the iOS SDK has been enabled since >=3.4.0 (and in 4.x)

**Comment by nenjamin2405** [comment] 2020-11-06 04:13
Hi @petrbela, I already updated to the latest version of react-native-google-cast 3.4.0 and I can see in the podfile.lock it's showing the latest SDK of Google Cast
```
- google-cast-sdk-no-bluetooth (4.5.0):
  - google-cast-sdk-no-bluetooth/Core (= 4.5.0)
  - GTMSessionFetcher/Core (~> 1.0)
  - Protobuf (~> 3.12)
- google-cast-sdk-no-bluetooth/Core (4.5.0):
  - GTMSessionFetcher/Core (~> 1.0)
  - Protobuf (~> 3.12)
- react-native-google-cast/NoBluetooth (3.4.0):
  - google-cast-sdk-no-bluetooth
  - React
  - react-native-google-cast/RNGoogleCast
- react-native-google-cast/RNGoogleCast (3.4.0):
  - React
- react-native-google-cast/NoBluetooth (from `../node_modules/react-native-google-cast/ios/`)
- react-native-google-cast:
  :path: "../node_modules/react-native-google-cast/ios/"
```

The function works fine on emulator using iOS 12.0 and 14.0, but when I test it on real device (using iOS 14.1), when the app is opened for the first time, the Permission Popup for Local Network (below image 1) is showed, and the cast icon is showed correctly, when I tap on the cast icon, it shows the popup (below image 2), when I tap ok, then the cast button will be disappeared from that moment and I cannot see it again afterward. 

**Image 1**
![image](https://user-images.githubusercontent.com/16648769/98325226-e0f30f80-2020-11eb-9b4b-2b845f1abfc6.png)

**Image 2**
![image](https://user-images.githubusercontent.com/16648769/98325213-d8023e00-2020-11eb-92bb-087cb5ed38c2.png)

Do you know what is the issue in this case :(

**Comment by namitonefc** [comment] 2020-12-18 07:40
@nenjamin2405 Did you found any way around this? I am facing the same issue.

**Comment by petrbela** [comment] 2020-12-18 09:23
@namitonefc You might try switching to v4 (`@next`) as it's coming out of beta in a few days anyway, and this problem is solved there. See https://react-native-google-cast.github.io/docs/getting-started/installation

**Comment by namitonefc** [comment] 2020-12-18 12:15
> @namitonefc You might try switching to v4 (`@next`) as it's coming out of beta in a few days anyway, and this problem is solved there. See https://react-native-google-cast.github.io/docs/getting-started/installation

@petrbela We are using a forked version of this repo. Rebasing shows a lot of conflicts. Is it possible for you to suggest the specific changes needed for this fix?

**Comment by petrbela** [comment] 2020-12-18 21:41
Hmm, I'm actually not sure about the cast button disappearing when opened for the first time. I'll need to retest that to see if it's fixed in v4 and how.

**Comment by KrzysztofGastolek** [comment] 2020-12-21 14:51
> Hmm, I'm actually not sure about the cast button disappearing when opened for the first time. I'll need to retest that to see if it's fixed in v4 and how.

I've tried V4 and it doesn't work on ios 14. No cast icon i CastButton. Also useCastState returns noDevicesAvailable.

**Comment by petrbela** [comment] 2020-12-21 18:15
@KrzysztofGastolek I might need a bit more context. I'm testing v4 on iOS 14 and it works there (though, there might still be some bugs). Can you double-check you've followed all the [installation](https://react-native-google-cast.github.io/docs/getting-started/installation) and [setup](https://react-native-google-cast.github.io/docs/getting-started/setup) instructions? Do you use a custom receiver? Does the CastButton show up in other apps (e.g. Google Home)? Is it a first build? A reproducible example would help debug the issue.

**Comment by KrzysztofGastolek** [comment] 2020-12-21 18:26
Ok, I've resolved my problem. I've deleted line `options.disableDiscoveryAutostart = true;` from `AppDelegate.m`. Now it works ok. It was my mistake. Sorry.

**Comment by petrbela** [comment] 2020-12-21 18:56
Oh, there is something weird about the `disableDiscoveryAutostart`. I'll need to update the documentation.

**Closed** 2021-01-02 16:15 UTC
Labels: feature-request
