### ISSUE TITLE
GoogleCast.launchExpandedControls() Crashes the App

### ISSUE THREAD

**Issue by MwareSolutons** [react-native-google-cast/react-native-google-cast#139] opened 2019-08-18 17:39 UTC
when I call GoogleCast.launchExpandedControls(); 
it crashes the app so hard there is no error information
using V3 library and RN 59.5

the casting does work normally

**Comment by flexgrip** [comment] 2019-08-23 15:06
I get this as well. Although not every time. Usually I can use the expanded controls once, then if I use them again after reconnecting, the entire app crashes.

**Comment by jedashford** [comment] 2019-08-23 18:11
We've been seeing this too. Appeared after upgrading to .60.5, although we're pretty sure thats not the cause especially since its a native crash. We're trying to track it down.

**Comment by jedashford** [comment] 2019-08-29 21:01
We're seeing this only on Android, although I haven't tested on apple. 

Here's our stacktrace:
```2019-08-29 11:48:48.813 19996-19996/com.vidangel.thechosen W/SupportMenuInflater: Cannot instantiate class: androidx.mediarouter.app.MediaRouteActionProvider
    java.lang.NoSuchMethodException: androidx.mediarouter.app.MediaRouteActionProvider.<init> [class android.content.Context]
        at java.lang.Class.getConstructor0(Class.java:2332)
        at java.lang.Class.getConstructor(Class.java:1728)
        at androidx.appcompat.view.SupportMenuInflater$MenuState.newInstance(SupportMenuInflater.java:549)
        at androidx.appcompat.view.SupportMenuInflater$MenuState.readItem(SupportMenuInflater.java:423)
        at androidx.appcompat.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:178)
        at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:128)
        at com.reactnative.googlecast.GoogleCastExpandedControlsActivity.onCreateOptionsMenu(GoogleCastExpandedControlsActivity.java:15)
        at android.app.Activity.onCreatePanelMenu(Activity.java:4074)
        at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:378)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2019-08-29 11:48:48.820 19996-19996/com.vidangel.thechosen D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2019-08-29 11:48:48.820 19996-19996/com.vidangel.thechosen E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vidangel.thechosen, PID: 19996
    java.lang.IllegalArgumentException: menu item with ID 2131230906 doesn't have a MediaRouteActionProvider.
        at com.google.android.gms.cast.framework.CastButtonFactory.zza(Unknown Source:16)
        at com.google.android.gms.cast.framework.CastButtonFactory.setUpMediaRouteButton(Unknown Source:2)
        at com.reactnative.googlecast.GoogleCastExpandedControlsActivity.onCreateOptionsMenu(GoogleCastExpandedControlsActivity.java:16)
        at android.app.Activity.onCreatePanelMenu(Activity.java:4074)
        at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:378)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)```

**Comment by jedashford** [comment] 2019-08-29 21:29
Ok we might have two different problems. Ours is on 0.60.5, only happens when proguard is on, so we narrowed it down to the androidx libs and adding this to proguard fixes the problem:
```
-keep class androidx.mediarouter.** { *; }
```
We might wanna update the documentation. 

As for the problem with @MwareSolutons , that might be something else since ours was specific to 0.60+ and androidx

**Comment by flexgrip** [comment] 2019-08-30 05:45
Where do you put that?

**Comment by jedashford** [comment] 2019-08-30 15:38
```
/android/app/proguard-rules.pro
```

I have proguard set to true for both release and debug builds. You should have something like this in your `android/app/build.gradle` file:
```
/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = true
def enableProguardInDebugBuilds = true
```

If `enableProguardInDebugBuilds` is set to true, then prooguard will strip out, what it thinks, is unused files in your dependencies. Adding the line mentioned above to the file tells proguard not to strip out those new androidx mediarouter files.

**Comment by jwenl** [comment] 2019-11-01 13:12
We are seeing this issue on IOS

**Comment by goncalo-assuncao** [comment] 2020-05-15 14:14
Is there a fix for this? This is still happening. Cast works fine, but the app crashes if we call the launchExpandedControls. Using the react-native 0.59 and react-native-google-cast 3.3.0

**Comment by reena-bacancy** [comment] 2020-06-16 05:05
> @goncalo-assuncao you find any solution or other way to by pass this issue.
> How you can cast?
> You can able to share any code

 GoogleCast.getCastDevice().then((data) => {
      if (data != undefined) {
        GoogleCast.castMedia(video);
        try {
          GoogleCast.launchExpandedControls();
        } catch (error) {
          
        }
      }
    });

**Comment by msal4** [comment] 2020-09-07 14:03
Still no solution?

**Comment by jonathanm-tkf** [comment] 2020-09-26 21:37
waiting for solution

**Comment by jonathanm-tkf** [comment] 2020-09-26 21:48
`libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<GCKUIButtonBarViewController: 0x7fa3f049ff30> returned nil from -traitCollection, which is not allowed.'
terminating with uncaught exception of type NSException`

**Comment by iansamz** [comment] 2020-10-19 19:27
Has anyone found a fix for this on ios?

**Comment by petrbela** [comment] 2022-02-26 22:57
I think this is working fine in the latest version.

**Closed by petrbela** 2022-02-26 22:57 UTC
Labels: iOS
