### ISSUE TITLE
How to stop casting when app is killed [iOS]

### ISSUE THREAD

**Issue by elinahovakimyan** [react-native-google-cast/react-native-google-cast#365] opened 2021-10-05 08:25 UTC
Hello! I am trying to end session once app is killed but clean up function of useEffect is not working on iOS. Any hint on how to stop casting once app is killed?

I tried using app state as well, however it becomes in active when changing to background as well, but I need to keep casting when the app is in background and stop only when it's swiped out/killed.

```
useEffect(() => {
    return () => {
      // Not being called on iOS
      sessionManager?.endCurrentSession && sessionManager?.endCurrentSession(true);
    };
  }, []);

```

Thanks!

**Comment by petrbela** [comment] 2021-10-05 15:25
If you manually kill the app, React Native won't have time to call JS callbacks, so the effect cleanup won't run.

What you can try instead is add something like this in your `AppDelegate.m` (haven't tested):

```obj-c
- (void)applicationWillTerminate:(UIApplication *)application {
  [GCKCastContext.sharedInstance.sessionManager endSessionAndStopCasting:true];
}
```

On Android you'll probably need to do something similar, i.e. in the termination callback call

```java
  CastContext.getSharedInstance().getSessionManager().endCurrentSession(true);
```

That being said, the idea behind Google Cast is that the app is just a remote client that connects to the "server" app running on the TV device. Terminating the client shouldn't automatically stop the media playing on the TV (you can even have multiple clients connected and controlling the media at the same time). But the decision is yours ;)

Anyway, I'm closing this issue as this is not a bug/feature this library should (or can) support.

**Closed by petrbela** 2021-10-05 15:25 UTC
