### ISSUE TITLE
How to cast Live stream to Chromecast

### ISSUE THREAD

**Issue by rangav** [react-native-google-cast/react-native-google-cast#58] opened 2018-03-03 13:27 UTC
Hi,

Thanks for the great library, How to cast live streams to Chromecast, i am getting CORS error when i try to cast youtube channel live stream

Thanks

**Comment by petrbela** [comment] 2019-01-11 11:42
Hi! Is this still a problem? You should be able to just use the HLS link and set the media like this:

```js
request.media.contentUrl = 'your stream URL.m3u8'
request.media.contentType = 'application/vnd.apple.mpegurl'
```

As this is ultimately not a problem with this library, I'm closing this issue.

**Comment by rangav** [comment] 2019-01-11 12:47
Hi @petrbela 

Have you testing the above solution for live stream?

**Comment by petrbela** [comment] 2019-01-11 13:14
We're using live stream from vimeo. YouTube should work, too; I highly doubt they wouldn't have CORS enabled.

If you're getting an error, it's probably an issue with your custom receiver. Can you post details?

**Comment by rangav** [comment] 2019-01-11 14:18
I am currently using Styled Media Receiver. I haven't used Custom Receiver.

Do you have sample customer receiver application code that i can use for testing live stream?

**Comment by rangav** [comment] 2019-01-11 15:41
Thanks @petrbela, Will try the Custom Receiver.

**Comment by petrbela** [comment] 2019-02-14 11:56
Hi @rangav, just an update, it looks like you shouldn't need a custom receiver for HLS. I'm investigating why it's not working.

**Comment by rangav** [comment] 2019-02-14 12:19
Thanks @petrbela. I didn’t get a chance to test with customer receiver. But if it works without custom receiver that would be great 👍.

**Comment by rangav** [comment] 2019-03-03 05:32
Hi @petrbela any update on this?

**Comment by rangav** [comment] 2019-04-16 21:16
I have testing with Custom Receiver and sent the content type = 'application/vnd.apple.mpegurl' from iOS app. Still getting Cors error. 

I did not know where to set in Custom receiver, but i check the console it geting the contentType application/vnd.apple.mpegurl.

Can you please test the below live video youtube url and let me know if its wokring for you.
https://www.youtube.com/watch?v=joZGEQhpqhA

I need to publish our app in  next few days. Can i contact you directly?

**Comment by rangav** [comment] 2019-04-16 21:20
This the error i am getting 

`Failed to load [VIdeoURl]: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '[hostedURL]' is therefore not allowed access.`

**Comment by jclrosa** [comment] 2019-06-07 14:00
Hi @petrbela, in the first place thanks for the great library!

I think that I am having a similar CORS issue. 
I can play successfully an `m3u8` format video without problems. 
However, when I check the URL of the video I want to play on a Testing Streaming URL website, I got a CORS issue. 

My question is what do I need to do in order to be able to play an `m3u8` URL video that has this CORS restriction. I have AirPlay integrated and didn't have any issue reproducing the video on an Apple TV. However, I think that Chromecast might behave differently.

**Comment by petrbela** [comment] 2019-06-07 19:55
Hi @jclrosa. I'm not sure what's the best path towards solving this on the client. Ultimately, CORS headers need to be set by the server, and browsers check for their presence. Apple TV, unlike Chromecast, doesn't run a web browser so it doesn't suffer from this issue.
What video hosting service are you using?

**Comment by jclrosa** [comment] 2019-06-12 09:43
Yeah, @petrbela that makes sense and explains the difference between Apple TV and Chromecast.
I am using AWS Cloudfront for video hosting service. If I need to set CORS headers by the server, do you know if there is any way of setting them to specifically for Chromcast, I mean what are the requirements in terms of headers that Chromecast requires for it to work?

**Comment by petrbela** [comment] 2019-06-12 15:14
@jclrosa Make sure you enable [OPTION requests](https://cl.ly/32e5280e8162) since that's the method CORS preflight uses. Also, Cloudfront is just a distribution; your origin server should set the appropriate CORS headers (for example, [follow this](https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) if you're using S3).

**Comment by jclrosa** [comment] 2019-07-09 16:16
@petrbela Thanks a lot for your suggestions! Yeah, by updating `Allowed HTTP Methods`, adding a CORS Policy to the S3 Bucket and updating the Cloudfront Behaviour definition I was able to play the video on `Testing Streaming URL` website like Radiant Media Player. 

However, when I try to reproduce it on Chromecast I just got a black screen. I don't know what any more options I should update. I think the CORS problem should be fixed since the video URL can be reproduced on a streaming website, and before it was not possible. There is any way to debug the chromecast device itself in order for me to obtain some more info about it is not reproducible?

**Comment by petrbela** [comment] 2019-07-09 16:21
Hmm not sure what could be causing that. You can debug a custom receiver app as described at https://developers.google.com/cast/docs/debugging. Since that's a plain old HTML page, you should be able to see why it's not working.

**Comment by jclrosa** [comment] 2019-07-12 13:51
@petrbela Finally got my video playing on Chromecast! I think that without accessing the Chromecast debug console I was never able to put it ok. The problem is that my videos have separate audio tracks, so I needed to build a custom receiver like is explained here: https://stackoverflow.com/questions/55224639/does-the-chromecast-support-casting-videos-from-reddit-hls-and-dash-videos.

So the solution was to implement the custom receiver. Thanks for all your help and great package :)

**Comment by Onlyward** [comment] 2020-06-19 12:11
Hello,

I've followed the discussion, but sadly I wasn't able to solve the live streaming issue.

Here is an example what I'm doing:

  GoogleCast.getCastDevice().then(console.log);
  GoogleCast.castMedia({
    mediaUrl: 'SOME_URL_WITH_LIVE_STREAMING.m3u8',
    imageUrl: 'http://some-image.com/01.png',
    title: 'Channel 001',
    subtitle: 'Channel 001',
    isLive: true,
  });
  GoogleCast.launchExpandedControls();

Smartphone is successfully connected with my Chromecast, but when I send the video using the code above is not working, and there is no errors message.

Do you guys have any idea how to implement live streaming using this package?

Thank you!

**Comment by airman00** [comment] 2020-11-15 19:45
Try this, contentType is important 

```
    GoogleCast.castMedia({
      mediaUrl: videoURL,
      imageUrl: image,
      title: 'title',
      subtitle: 'subtitle',
      studio: 'studio name',
      streamDuration: 0, // seconds
      contentType: 'video/m3u',
})     
```

**Comment by alihussnain-git** [comment] 2021-03-25 13:04
@petrbela can you please inform if any update here?
https://cdn-broadcast100-fra.tokbox.com/12913/12913_0b697e8f-08cd-4acc-b4b6-34fe67fd7690.smil/playlist.m3u8
I have this format URL bus its not working on chromecast

**Comment by petrbela** [comment] 2022-02-26 22:06
I'll close this as it doesn't seem to be an issue with the library but feel free to continue discussing solutions.

**Closed by petrbela** 2022-02-26 22:06 UTC

**Comment by amf-paulinho** [comment] 2022-03-23 23:26
Guys Sorry to restart this discussion. I cant cast Vimeo Direct Links, A I missing something  ?  

if (client) {
	client.loadMedia({
		mediaInfo: {
			contentUrl:
				'https://vod-progressive.akamaized.net/exp=1648238440~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F3309%2F27%2F691545734%2F3193649126.mp4~hmac=7fced3c96cb9fbf817ed8e259a0c2455d405fbc102256e5b10694b8aa87c8a33/vimeo-prod-skyfire-std-us/01/3309/27/691545734/3193649126.mp4', //videoPlayer.current.source.uri,
			contentType: 'video/mp4',
			metadata: {
				images: [
					{
						url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/images/480x270/BigBuckBunny.jpg',
					},
				],
				title: 'Big Buck Bunny',
				subtitle:
					'A large and lovable rabbit deals with three tiny bullies, led by a flying squirrel, who are determined to squelch his happiness.',
				studio: 'Blender Foundation',
				type: 'movie',
			},
			streamDuration: 596, // seconds
		},
		startTime: 10, // seconds
	})
}

ps: If I cast the Bunny Video, it works fine.

**Comment by nriccar** [comment] 2022-04-20 15:34
@jclrosa [jclrosa](https://github.com/jclrosa) How did you manage to set cors on s3 and cloudfront cdn? Thanks!
